image: atlassian/default-image:2
pipelines:
  branches:
      master:
        - step:
           name: Set version info
           script:
               - export COMMIT=$(echo $BITBUCKET_COMMIT | cut -c1-7)
               - export RELEASE_VERSION="1.$BITBUCKET_BUILD_NUMBER.0-$COMMIT"
               - export PACKAGE=$BITBUCKET_REPO_SLUG.$RELEASE_VERSION
               - echo $RELEASE_VERSION > RELEASE_VERSION.txt
               - echo $PACKAGE > PACKAGE.txt
           artifacts:
               - RELEASE_VERSION.txt
               - PACKAGE.txt
        - step:
           name: Build Package
           script:
               - curl -sL https://deb.nodesource.com/setup_12.x | bash -
               - apt update && apt-get install -y zip
               - zip -r PACKAGE.zip .
           artifacts:
               - PACKAGE.zip
        - step:
           name: Create Octopus Release
           image: octopusdeploy/octo:latest-alpine
           script:
               - apk update
               - RELEASE_VERSION=$(cat RELEASE_VERSION.txt)
               - PACKAGE=$(cat PACKAGE.txt)
               - mv PACKAGE.zip $PACKAGE.zip
               - octo push --package $PACKAGE.zip --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY
               - octo create-release --project appsecmonitor --version $RELEASE_VERSION --package appsecmonitor:$RELEASE_VERSION --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY